version: '3'
services:
  app:
    image: svdimov85/students-jenkins:1.0.0
    ports:
      - "3030:8081" # Map port 3030 on the host to port 3030 in the container
    environment:
      - NODE_ENV=production
